from os import path

FPS = 4
SCREENWIDTH = 880
SCREENHEIGHT = 880
CELLSIZE = 80
WFCWEIGHTS = [100,30,10,5,1,1]
MAXWEIGHT = 100000
MINWEIGHT = 0.0000001
MAIN_FOLDER = path.dirname(__file__)
ASSETS_FOLDER = path.join(MAIN_FOLDER, "assets")
TILES_FOLDER = path.join(ASSETS_FOLDER, "tiles")
CREATURE_FOLDER = path.join(ASSETS_FOLDER, "creatures")
BERRYIMG = path.join(ASSETS_FOLDER, "objects", "berrybush.png")
NONTRAVERSABLE_MOVEMENT_MODIFYER = 1000000

#Animal Stats
CREATURECOUNT = 2
BASE_ENERGY = 500
BASE_HEALTH = 100
URGE_HUNT = 100
URGE_REPRODUCE = 100
MAXWANDERDISTANCE = 10
BASECHOICEWEIGHTS = [1,1,1] #eat,wander,reproduce
MAXCHOICEWEIGHT = 200
LOSSPERSTEP = 2
BERRYENERGYREFILL = 100
LOWENERGYTHRESHOLD_PERCENT = 0.4
LOWENERGYTHRESHOLD = BASE_ENERGY * LOWENERGYTHRESHOLD_PERCENT

